/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.api;

public class Main {
    public static void main(String[] args) {

    	Json json = new Json();
    	Api api = new Api("http://localhost:8080/api/example");

    	ApiRequestForm requestForm = new ApiRequestForm();
    	requestForm.setId(2);
    	requestForm.setFirstName("田中");
    	requestForm.setLastName("太郎");
    	String jsonParam = json.pojoToJson(requestForm);
    	String jsonResponce = api.requestByPost(jsonParam);
    	ApiResponse response = (ApiResponse) json.jsonToPojo(jsonResponce);

    	if (response.getCode() == 200) {
    		System.out.println("API連携正常終了");
    	} else {
    		System.out.println("API連携異常終了");
    	}

    }
}
